"""
ARP Detector Module.

Provides the ARPDetector class, which maintains an in-memory mapping of IP
addresses to MAC addresses to detect ARP spoofing and poisoning anomalies.
"""
import logging
from typing import Optional, Dict, Any

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class ARPDetector:
    """
    Detects ARP spoofing/poisoning attacks by monitoring IP to MAC address mappings.
    Maintains state to identify when an IP address suddenly resolves to a new MAC address.
    """
    
    def __init__(self) -> None:
        """
        Initializes the ARPDetector.
        Maintains an in-memory mapping of IP addresses to MAC addresses
        to detect ARP spoofing/poisoning anomalies.
        """
        # In-memory IP -> MAC mapping table used during normal operation
        self.ip_mac_table: Dict[str, str] = {}
        # Separate table used when test_mode is enabled – isolates state from real traffic
        self._test_ip_mac_table: Dict[str, str] = {}
        # Flag indicating whether the detector is in safe-testing mode
        self.test_mode: bool = False

    def enable_test_mode(self, enable: bool = True) -> None:
        """
        Turn safe-testing mode on or off.
        
        When enabled, the detector uses an isolated mapping table so that
        injected test packets never pollute the production ARP table.
        
        Args:
            enable (bool): True to enable test mode, False to disable.
        """
        self.test_mode = enable
        # Reset the test table when enabling – ensures a clean start
        if enable:
            self._test_ip_mac_table.clear()

    def _get_table(self) -> Dict[str, str]:
        """Return the appropriate IP->MAC table based on the current mode."""
        return self._test_ip_mac_table if self.test_mode else self.ip_mac_table

    def process_packet(self, packet_details: Dict[str, Any]) -> Optional[str]:
        """
        Processes a single packet's details to monitor ARP packets and detect spoofing.
        
        Args:
            packet_details (Dict[str, Any]): Dictionary containing extracted packet details 
                                             (expected to be generated by PacketAnalyzer).
                                             
        Returns:
            Optional[str]: An alert message string if spoofing is detected, otherwise None.
        """
        try:
            # We only care about ARP packets
            if packet_details.get("protocol") != "ARP":
                return None
            
            src_ip = packet_details.get("arp_src_ip")
            src_mac = packet_details.get("arp_src_mac")
            
            # Ensure both IP and MAC are present and valid
            if not src_ip or not src_mac:
                return None
                
            # Ignore the "0.0.0.0" IP address which is often used in ARP probes (duplicate address detection)
            if src_ip == "0.0.0.0":
                return None

            table = self._get_table()

            # Check if we have already recorded a MAC address for this IP
            if src_ip in table:
                known_mac = table[src_ip]
                
                # If the newly observed MAC address is different from the known MAC address,
                # this is a strong indicator of an ARP spoofing/poisoning attack.
                if known_mac != src_mac:
                    alert_msg = f"[ALERT] Possible ARP Spoofing Detected! IP {src_ip} changed MAC from {known_mac} to {src_mac}."
                    
                    # Update the table to the new MAC to prevent spamming the exact same alert endlessly.
                    table[src_ip] = src_mac
                    
                    return alert_msg
            else:
                # First time seeing this IP, record its MAC address in the table
                table[src_ip] = src_mac
                
        except Exception as e:
            logging.error(f"Error in ARP detection processing: {e}")
            
        return None

    # ---------------------------------------------------------------------
    # Testing helpers – safe mode only
    # ---------------------------------------------------------------------
    def test_spoof_sequence(self, src_ip: str, original_mac: str, spoofed_mac: str) -> Optional[str]:
        """
        Simulate an ARP spoofing scenario in safe-testing mode.
        
        This method does **not** affect the production `ip_mac_table`.
        
        Args:
            src_ip (str): The simulated source IP address.
            original_mac (str): The initial MAC address.
            spoofed_mac (str): The spoofed (changed) MAC address.
            
        Returns:
            Optional[str]: The alert message generated on the second (conflicting) packet,
                           or None if something went wrong.
        """
        # Ensure test mode is active – we use the isolated table
        self.enable_test_mode(True)

        # First packet – registers the original mapping
        first_packet = {
            "protocol": "ARP",
            "arp_src_ip": src_ip,
            "arp_src_mac": original_mac,
        }
        self.process_packet(first_packet)  # should just record, no alert

        # Second packet – conflicting MAC triggers alert
        second_packet = {
            "protocol": "ARP",
            "arp_src_ip": src_ip,
            "arp_src_mac": spoofed_mac,
        }
        alert = self.process_packet(second_packet)
        
        # Turn off test mode to avoid leaking state
        self.enable_test_mode(False)
        return alert
