"""
Logger Manager Module.

Handles persistent logging of packets and security alerts to text files.
Supports JSON-encoded packet logs and plain-text alert logs.
"""
import os
import json
import logging
from datetime import datetime
from typing import Dict, Any

# Configure a module-level logger for internal debugging (optional)
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Base directory for all log files – it lives next to this module
BASE_LOG_DIR = os.path.join(os.path.dirname(__file__), "logs")

# Ensure the logs directory exists once at import time
try:
    os.makedirs(BASE_LOG_DIR, exist_ok=True)
except Exception as e:
    # If we can't create the folder we fall back to the current working directory
    logging.error(f"Failed to create logs directory '{BASE_LOG_DIR}': {e}")
    BASE_LOG_DIR = os.getcwd()

# Filenames for the two log types
PACKET_LOG_FILE = os.path.join(BASE_LOG_DIR, "packet_logs.txt")
ALERT_LOG_FILE = os.path.join(BASE_LOG_DIR, "arp_alerts.txt")


def _write_line_safely(file_path: str, line: str) -> None:
    """Helper that writes a single line to *file_path*.
    It catches IO errors and logs them instead of propagating.
    """
    try:
        with open(file_path, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    except PermissionError as exc:
        logging.error(f"Permission denied writing to log file '{file_path}': {exc}. Check if file is open.")
    except Exception as exc:
        logging.error(f"Unable to write to log file '{file_path}': {exc}")


def log_packet(packet_info: Dict[str, Any]) -> None:
    """Append a JSON-encoded packet record to *packets.log*.

    The log line format is::
        <ISO-8601 timestamp> | PACKET | <json-dump of packet_info>

    *packet_info* is expected to be the dictionary generated by
    ``PacketSniffer`` (it already contains a ``timestamp`` field, but we
    prepend our own timestamp for consistency).
    """
    timestamp = datetime.utcnow().isoformat() + "Z"
    try:
        json_payload = json.dumps(packet_info, ensure_ascii=False)
        line = f"{timestamp} | PACKET | {json_payload}"
        _write_line_safely(PACKET_LOG_FILE, line)
    except Exception as exc:
        logging.error(f"Failed to log packet: {exc}")


def log_alert(alert_msg: str) -> None:
    """Append a plain-text alert to *alerts.log*.

    The log line format is::
        <ISO-8601 timestamp> | ALERT | <alert_msg>
    """
    timestamp = datetime.utcnow().isoformat() + "Z"
    line = f"{timestamp} | ALERT | {alert_msg}"
    _write_line_safely(ALERT_LOG_FILE, line)
